In [1]:
import numpy as np
import pandas as pd

---
### Setting up basic matrices:
The Pauli matrices are the four 2x2 matrices, I, X, Y, Z.
For this example, we have a 4x4 Hamiltonian that is decomposed into IZ, ZI, XX, YY, and ZZ terms (this notation is not matrix multiplication--it is a Kronecker product, which takes two 2x2 matrices and gives a 4x4 matrix).

In [2]:
I = np.eye(2)
X = np.array([[0., 1.],
              [1., 0.]])
Y = np.array([[0., -1j],
              [1j, 0.]])
Z = np.array([[1., 0.],
              [0., -1.]])

In [3]:
IZ = np.kron(I, Z)
print(IZ)

[[ 1.  0.  0.  0.]
 [ 0. -1.  0. -0.]
 [ 0.  0.  1.  0.]
 [ 0. -0.  0. -1.]]


In [4]:
ZI = np.kron(Z, I)
print(ZI)

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0. -1. -0.]
 [ 0.  0. -0. -1.]]


In [5]:
XX = np.kron(X, X)
print(XX)

[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]


In [6]:
YY = np.kron(Y, Y)
print(YY)

[[ 0.+0.j  0.-0.j  0.-0.j -1.+0.j]
 [ 0.+0.j  0.+0.j  1.-0.j  0.-0.j]
 [ 0.+0.j  1.-0.j  0.+0.j  0.-0.j]
 [-1.+0.j  0.+0.j  0.+0.j  0.+0.j]]


In [7]:
ZZ = np.kron(Z, Z)
print(ZZ)

[[ 1.  0.  0.  0.]
 [ 0. -1.  0. -0.]
 [ 0.  0. -1. -0.]
 [ 0. -0. -0.  1.]]


----
### Hamiltonian
We consider the Hamiltonian:
$H = IZ + ZI - XX - YY + ZZ$

In [8]:
H = IZ + ZI - XX - YY + ZZ
print(H)

[[ 3.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j -1.+0.j -2.+0.j  0.+0.j]
 [ 0.+0.j -2.+0.j -1.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j -1.+0.j]]


---
### Measuring an observable
An observable is a matrix that we can measure against a state $\vec{\psi}$. The Hamiltonian is an observable. So are the Pauli terms that it is written as a sum of.

To measure some observable matrix $M$ with respect to a state $\vec{\psi}$, we just compute $\vec{\psi}^{\dagger} M \vec{\psi}$. The $\dagger$ means conjugate transpose = transpose the matrix and then take complex conjugates. In this specific example, all the numbers are real, so it happens to be the same as an ordinary matrix transpose.

Here is a helper method that does everything for us:

In [9]:
def expected_value(M, state):
    return np.asmatrix(state).getH() @ M @ state  # .getH() does conjugate tranpose

---
### Let's try for $\vec{\psi} = [0, 1, 0, 0]^T$

In [10]:
state = np.array([[0.], [1.], [0.], [0.]])

#### Method 1: measure $H$ directly
A quantum computer can't actually measure $H$ directly, but let's just check what the answer should be.

In [11]:
print(expected_value(H, state))

[[-1.+0.j]]


#### Method 2: linearity of expectation
A quantum computer can compute the Pauli observables though. So let's use linearity of expectation instead:

In [12]:
IZ_expectation = expected_value(IZ, state)
ZI_expectation = expected_value(ZI, state)
XX_expectation = expected_value(XX, state)
YY_expectation = expected_value(YY, state)
ZZ_expectation = expected_value(ZZ, state)
print(IZ_expectation, ZI_expectation, XX_expectation, YY_expectation, ZZ_expectation)
print(IZ_expectation + ZI_expectation - XX_expectation - YY_expectation + ZZ_expectation)

[[-1.]] [[1.]] [[0.]] [[0.+0.j]] [[-1.]]
[[-1.+0.j]]


Yup, we got -1 both ways!

---
### Variances / Covariances

In [13]:
def variance(M, state):
    # variances is <M^2> - <M>^2
    return expected_value(M @ M, state) - expected_value(M, state) ** 2

def covariance(M_1, M_2, state):
    return expected_value(M_1 @ M_2, state) - expected_value(M_1, state) * expected_value(M_2, state)

The cells below show that:
- Var(H) = 4
- Var(IZ) + Var(ZI) + Var(XX) + Var(YY) + Var(ZZ) = 2 -- not equal because we need to account for covariances
- the summed covariances do indeed equal 4. Note that the XX and ZZ

In [14]:
variance(H, state)

matrix([[4.+0.j]])

In [15]:
variance(IZ, state)

matrix([[0.]])

In [16]:
variance(ZI, state)

matrix([[0.]])

In [17]:
variance(XX, state)

matrix([[1.]])

In [18]:
variance(YY, state)

matrix([[1.+0.j]])

In [19]:
variance(ZZ, state)

matrix([[0.]])

In [20]:
terms, coefficients = [IZ, ZI, XX, YY, ZZ], [1., 1., -1., -1., 1.]
total = np.array([[0.+0.j]])
for i in range(5):
    for j in range(5):
        cov = covariance(terms[i], terms[j], state)
        if cov != 0:
            print(cov, i, j)
            total += (coefficients[i] * coefficients[j] * covariance(terms[i], terms[j], state))
print('Variance from summed covariances is %s' % total)

[[1.]] 2 2
[[1.+0.j]] 2 3
[[1.+0.j]] 3 2
[[1.+0.j]] 3 3
Variance from summed covariances is [[4.+0.j]]


----
### Different State, $\vec{\psi} = [0.43 - 0.16i, -0.49, 0.44i, -0.39 + 0.46i]$

In [21]:
state = np.array([[0.43 - 0.16j], [-0.49], [0.43j], [-0.39 + 0.46j]])

In [22]:
variance(H, state)

matrix([[4.35848816-2.22044605e-16j]])

In [23]:
variance(IZ, state), variance(ZI, state), variance(-XX, state), variance(-YY, state), variance(ZZ, state)

(matrix([[0.95576944+0.j]]),
 matrix([[0.989596+0.j]]),
 matrix([[0.76629724+6.6974204e-18j]]),
 matrix([[0.76629724+0.j]]),
 matrix([[0.97693936+0.j]]))

In [24]:
print(covariance(IZ, ZI, state))
print(covariance(IZ, ZZ, state))
print(covariance(ZI, ZZ, state))
print(covariance(-XX, -YY, state))
print(covariance(-XX, ZZ, state))
print(covariance(-YY, ZZ, state))

[[0.1287768+0.j]]
[[-0.06690672+0.j]]
[[-0.1937784+0.j]]
[[0.08370276-3.3487102e-18j]]
[[0.41059608+1.03528297e-18j]]
[[-0.41059608+6.9388939e-18j]]


In [25]:
# Setting 1 (measure all terms separately) would require a number of state preparations equal to:
5 * (0.95576944 + 0.989596 + 0.76629724 + 0.76629724 + 0.97693936)

22.2744964

In [26]:
# Setting 2 (measure {XX}, {YY, ZZ}, {IZ, ZI}) would require a number of state preparations equal to:
3 * (0.95576944 + 0.989596 + 0.76629724 + 0.76629724 + 0.97693936 + 2*0.08370276 + 2*0.1287768)

14.6395752

In [27]:
# Setting 3 (measure {XX, YY, ZZ}, {IZ, ZI}) would require a number of state preparations equal to:
2 * (0.95576944 + 0.989596 + 0.76629724 + 0.76629724 + 0.97693936 + 2*0.08370276 + 2*0.41059608 + 2*-0.41059608 + 2*0.1287768)

9.7597168

### Programatically finding optimal groupings

In [28]:
def variance_grouping(grouping, state):
    """
    Computes the variance of a grouping, via the formula
             Var(A+B) = Var(A) + Var(B) + 2*Cov(A,B)
    Inputs:
       Grouping (as a list, e.g. [-XX, -YY, ZZ])
       State (as a np.array, e.g. np.array([[0.], [1.], [0.], [0.]]))
    """
    running_variance = sum([variance(term, state) for term in grouping])
    grouping_size = len(grouping)
    for i in range(grouping_size):
        for j in range(i):
            running_variance += 2*covariance(grouping[i], grouping[j], state)
    return(np.asscalar(running_variance))

In [29]:
# # Credit to: https://stackoverflow.com/questions/19368375/set-partitions-in-python
def partition(collection):
    if len(collection) == 1:
        yield [ collection ]
        return

    first = collection[0]
    for smaller in partition(collection[1:]):
        # insert `first` in each of the subpartition's subsets
        for n, subset in enumerate(smaller):
            yield smaller[:n] + [[ first ] + subset]  + smaller[n+1:]
        # put `first` in its own subset 
        yield [ [ first ] ] + smaller


In [34]:
def calculate_variance_all_partitions(term_set, state):
    """
    Computes the variance of every possible partition of a set of terms.
    Inputs:
        term_set: list of *strings*, e.g. ["-XX", "-YY", "ZZ", "IZ", "ZI"]
        state: as a np.array, e.g. np.array([[0.], [1.], [0.], [0.]]))
    """
    evaled_term_set = [eval(term) for term in term_set]
    term_list = []
    variance_list = []
    for pp in partition(list(range(len(term_set)))):
         term_list.append([list(np.array(term_set)[grouping]) for grouping in pp])
         variance_list.append(sum([variance_grouping(np.array(evaled_term_set)[indices], state)*len(pp) for indices in pp]))
    partition_list = pd.DataFrame({'partition': term_list, 'variance': variance_list}).sort_values(by=["variance"])
    return(partition_list)

# Aspuru-Guzik example
test_term_set = ["-XX", "-YY", "ZZ", "IZ", "ZI"]
state = np.array([[0.43 - 0.16j], [-0.49], [0.43j], [-0.39 + 0.46j]])

calculate_variance_all_partitions(test_term_set, state)


partition  \
0           [[-XX, -YY, ZZ, IZ, ZI]]   
1         [[-XX], [-YY, ZZ, IZ, ZI]]   
28        [[-XX, IZ], [-YY, ZZ, ZI]]   
16        [[-YY, ZZ, IZ], [-XX, ZI]]   
6         [[-YY, ZZ], [-XX, IZ, ZI]]   
25        [[-XX, -YY, IZ], [ZZ, ZI]]   
29        [[IZ], [-XX, -YY, ZZ, ZI]]   
2         [[-XX, -YY], [ZZ, IZ, ZI]]   
19        [[ZZ, IZ], [-XX, -YY, ZI]]   
15        [[-XX, -YY, ZZ, IZ], [ZI]]   
30      [[-XX], [IZ], [-YY, ZZ, ZI]]   
26        [[-YY, IZ], [-XX, ZZ, ZI]]   
9         [[ZZ], [-XX, -YY, IZ, ZI]]   
5         [[-XX, -YY, ZZ], [IZ, ZI]]   
17      [[-XX], [-YY, ZZ, IZ], [ZI]]   
8         [[-XX, ZZ], [-YY, IZ, ZI]]   
18        [[-XX, ZZ, IZ], [-YY, ZI]]   
3         [[-YY], [-XX, ZZ, IZ, ZI]]   
37      [[-YY, ZZ], [IZ], [-XX, ZI]]   
36      [[-YY, ZZ], [-XX, IZ], [ZI]]   
27      [[-XX], [-YY, IZ], [ZZ, ZI]]   
7       [[-XX], [-YY, ZZ], [IZ, ZI]]   
4       [[-XX], [-YY], [ZZ, IZ, ZI]]   
20      [[-XX], [ZZ, IZ], [-YY, ZI]]   
31      [[-XX, -YY], [IZ], [ZZ, ZI]]   
32      [[-YY], [-XX, IZ], [ZZ, ZI]]   
41      [[ZZ], [-YY, IZ], [-XX, ZI]]   
23      [[-YY], [ZZ, IZ], [-XX, ZI]]   
10      [[-XX], [ZZ], [-YY, IZ, ZI]]   
21      [[-XX, -YY], [ZZ, IZ], [ZI]]   
44      [[ZZ], [-XX, IZ], [-YY, ZI]]   
40      [[ZZ], [-XX, -YY, IZ], [ZI]]   
45      [[ZZ], [IZ], [-XX, -YY, ZI]]   
35      [[-XX, -YY, ZZ], [IZ], [ZI]]   
38    [[-XX], [-YY, ZZ], [IZ], [ZI]]   
11      [[-XX, -YY], [ZZ], [IZ, ZI]]   
33      [[-YY], [IZ], [-XX, ZZ, ZI]]   
13      [[-YY], [ZZ], [-XX, IZ, ZI]]   
39      [[-XX, ZZ], [-YY, IZ], [ZI]]   
43      [[-XX, ZZ], [IZ], [-YY, ZI]]   
22      [[-YY], [-XX, ZZ, IZ], [ZI]]   
34    [[-XX], [-YY], [IZ], [ZZ, ZI]]   
12      [[-YY], [-XX, ZZ], [IZ, ZI]]   
42    [[-XX], [ZZ], [-YY, IZ], [ZI]]   
24    [[-XX], [-YY], [ZZ, IZ], [ZI]]   
46    [[-XX], [ZZ], [IZ], [-YY, ZI]]   
50    [[-YY], [ZZ], [IZ], [-XX, ZI]]   
47    [[-XX, -YY], [ZZ], [IZ], [ZI]]   
49    [[-YY], [ZZ], [-XX, IZ], [ZI]]   
14    [[-XX], [-YY], [ZZ], [IZ, ZI]]   
48    [[-YY], [-XX, ZZ], [IZ], [ZI]]   
51  [[-XX], [-YY], [ZZ], [IZ], [ZI]]   

                                        variance  
0                                (4.35848816+0j)  
1        (6.148306400000001+2.1663999999999994j)  
28                                (6.7054168+0j)  
16                        (6.786671199999999+0j)  
6                 (8.373996-2.1663999999999994j)  
25                            (8.469496-3.3712j)  
29                            (8.469496+3.3712j)  
2                                (8.71697632+0j)  
19                   (8.976982719999999+3.3712j)  
15                          (8.97698272-3.3712j)  
30                   (9.454682159999999+4.1532j)  
26                        (9.563953119999999+0j)  
9                                 (9.7597168+0j)  
5             (9.7597168+3.189670749748075e-17j)  
17       (9.896237999999999-0.9036000000000001j)  
8       (10.475815520000001+2.1663999999999994j)  
18                              (10.49767216+0j)  
3       (10.616024159999998-2.1663999999999994j)  
37      (11.184890159999998+0.9036000000000001j)  
36                          (11.5045644-4.1532j)  
27              (11.5985844-0.9036000000000001j)  
7           (11.67378216+6.172562461159714e-17j)  
4           (12.57324792+2.009226118815377e-17j)  
20                  (12.679488719999998+4.1532j)  
31                                (12.704244+0j)  
32                         (12.80547048-4.1532j)  
41                               (13.0450236+0j)  
23             (13.24702632+0.9036000000000001j)  
10               (13.2501468+3.249599999999999j)  
21                              (13.46547408+0j)  
44                              (13.68437208+0j)  
40                  (13.866914399999999-5.0568j)  
45                  (13.866914399999999+5.0568j)  
35           (13.8669144+4.784506124622112e-17j)  
38   (14.534828479999998+8.230083281546286e-17j)  
11                               (14.6395752+0j)  
33             (14.