In [1]:
import qutip
import numpy as np

In [2]:
H2_hamiltonian_string = """ZZ
0.011280
ZI
0.397936
IZ
0.397936
XX
0.180931"""

In [3]:
def parse_hamiltonian_string(hamiltonian_string):
    lines = hamiltonian_string.split()
    assert len(lines) % 2 == 0
    terms = []
    while len(lines) > 0:
        coefficient = float(lines.pop())
        pauli_string = lines.pop()
        terms.append(HamiltonianTerm(pauli_string, coefficient))
    return terms
    
class HamiltonianTerm(object):
    def __init__(self, pauli_string, coefficient):
        self.pauli_string = pauli_string
        self.coefficient = coefficient
    
    def __repr__(self) -> str:
        return '%s %s' % (self.coefficient, self.pauli_string)

    def __str__(self) -> str:
        return '%s %s' % (self.coefficient, self.pauli_string)
    
    def get_matrix(self):
        return self.coefficient * pauli_string_to_matrix(self.pauli_string)
    
def _to_matrix(pauli_char):
    if pauli_char == 'X':
        return qutip.sigmax()
    elif pauli_char == 'Y':
        return qutip.sigmay()
    elif pauli_char == 'Z':
        return qutip.sigmaz()
    return qutip.identity(2)
    
def pauli_string_to_matrix(pauli_string):
    matrices = []
    for char in pauli_string:
        matrices.append(_to_matrix(char))
    return qutip.tensor(matrices)
    

In [4]:
hamiltonian = qutip.Qobj()
for term in parse_hamiltonian_string(H2_hamiltonian_string):
    hamiltonian += term.get_matrix()

In [5]:
hamiltonian

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 0.807152  0.        0.        0.180931]
 [ 0.       -0.01128   0.180931  0.      ]
 [ 0.        0.180931 -0.01128   0.      ]
 [ 0.180931  0.        0.       -0.784592]]

In [54]:
rand_ket = qutip.tensor(qutip.rand_ket_haar(2), qutip.rand_ket_haar(2))

In [58]:
rand_ket

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[-0.03917048+0.14447644j]
 [-0.60015626-0.4059692j ]
 [ 0.12370476-0.05677852j]
 [ 0.0659824 +0.65552526j]]

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[-0.21102737+0.14461763j]
 [-0.65772556-0.62013766j]
 [-0.19855771+0.15014109j]
 [ 0.15422237-0.17784125j]]

In [101]:
energies = []
for _ in range(10):
    rand_ket = qutip.rand_ket_haar(4, dims=[[2, 2], [1, 1]])
    energy = 0.0
    for term in parse_hamiltonian_string(H2_hamiltonian_string):
        energy += qutip.expect(term.get_matrix(), rand_ket)
    energies.append(energy)
min(energies)

-0.2650946243524725

In [108]:
energies = []
min_energy = 0
for _ in range(1000000):
    rand_ket = qutip.rand_ket_haar(4, dims=[[2, 2], [1, 1]])
    energy = qutip.expect(hamiltonian, rand_ket)
    if energy < min_energy:
        print(energy)
        min_energy = energy

-0.22543181558716552
-0.32019093100700935
-0.49328826964513134
-0.60920475414684
-0.7573041673691369
-0.7668839368426019
-0.7729596680419163
-0.7747401457343255
-0.7785598625708484
-0.7899015775176655
-0.7945268361285881


KeyboardInterrupt: 

In [98]:
hamiltonian

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 0.807152  0.        0.        0.180931]
 [ 0.       -0.01128   0.180931  0.      ]
 [ 0.        0.180931 -0.01128   0.      ]
 [ 0.180931  0.        0.       -0.784592]]

In [33]:
qutip.rand_ket(1)

Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[-0.29003086+0.9570173j]]

In [ ]:
qutip.identity(2)

In [ ]:
qutip.sigmaz() + qutip.sigmax()

In [8]:
matrices = [qutip.identity(2), qutip.sigmax(), qutip.sigmay(), qutip.sigmaz()]
terms = []
for m1 in matrices:
    for m2 in matrices:
        terms.append([m1, m2])

In [7]:
qutip.commutator(terms[3], terms[17]).norm()

IndexError: list index out of range